title: "Kazbek Hashimov â€” Portfolio"
description: "IT student @ ADA University"
url: "https://kazbek256.github.io"
baseurl: "/SITE-1101-2-"

# Pick ONE GitHub Pages theme:
theme: jekyll-theme-minimal